apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /data/postgres-1
  claimRef:
    namespace: dev
    name: postgres-data-postgres-1
