apiVersion: v1
kind: LimitRange
metadata:
  name: dev-default-limits
  namespace: dev
spec:
  limits:
    - type: Container
      default:
        cpu: "100m"
        memory: "128Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"

